language: node_js
dist: trusty
addons:
  apt:
    packages:
      - libnss3
branches:
  only:
    - staging
    - master
node_js:
  - "8.9.1"
services:
  - redis-server
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3